### ISSUE TITLE
namespace name should be in capital

### ISSUE THREAD

**Issue by TheSYNcoder** [ju-db/biscuitdb#5]
In the line https://github.com/ju-db/biscuitdb/blob/7c245d6f1927a95ae74da189d6d5613e4f488e60/src/include/main/biscuit.h#L6

could be something like 
```
namespace BiscuitDB{
```

Specially PascalCase is preferred.
https://stackoverflow.com/questions/13035410/naming-guideline-for-namespaces-when-company-has-all-caps

Please submit your opinions.

**Comment by bisakhmondal** [comment]
Thanks for the concern. 
Don't use it. Makes a nasty workflow.

>Namespace names are all lower-case, with words separated by underscores. Top-level namespace names are based on the project name

Ref: https://google.github.io/styleguide/cppguide.html#Namespace_Names
Closing it.
