### ISSUE TITLE
Merge commits

### ISSUE THREAD

**Issue by noob77777** [ju-db/biscuitdb#7]
# Feature Request
## Summary
Use squash merge for pull requests instead of merge commits. I think the commit history looks cleaner that way.

**Comment by TheSYNcoder** [comment]
Cool ✅

**Comment by bisakhmondal** [comment]
Ik, I thought u peeps would be angry for shadowing your lots of commits to single on ;)
BTW it's no big deal, lol😂

**Comment by Satyam6623165** [comment]
Got it
